name: Build-ARM-Binary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 必须是 v4

      - name: Install Compiler and Libs
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi libmbedtls-dev -y

      - name: Compile Code
        run: |
          # 使用 *.c 自动匹配文件名，避免中文乱码导致找不到文件
          arm-linux-gnueabi-gcc *.c -o alice-sms -lpthread -lmbedtls -lmbedcrypto -static

      - name: Upload Result
        uses: actions/upload-artifact@v4 # 必须是 v4
        with:
          name: alice-sms-arm-binary
          path: alice-sms
