name: Build-ARM-Binary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 更新到 v4

      - name: Install Compiler and Libs
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi libmbedtls-dev -y

      - name: Compile Code
        run: |
          # 请确保您上传的 C 文件名是 alice.c，如果不是，请改下面这一行
          arm-linux-gnueabi-gcc alice-sms-pusher源码.c -o alice-sms -lpthread -lmbedtls -lmbedcrypto -static

      - name: Upload Result
        uses: actions/upload-artifact@v4 # 修正：必须使用 v4
        with:
          name: alice-sms-arm-binary
          path: alice-sms
